### ISSUE TITLE
update link of linonetwo

### ISSUE THREAD

**Issue by linonetwo** [kebifurai/TiddlyResearch#1]
Hi, thanks for your good work!

I can see you have linonetwo in your credit list, but it actually point to my friend borber's wiki.

Can you update it to my wiki https://onetwo.ren/wiki
Or my plugin repo https://github.com/linonetwo/tiddlywiki-plugins
Or my tg note https://github.com/tiddly-gittly/TiddlyGit-Desktop

Thanks!

**Comment by postkevone** [comment]
I'm so sorry I thought that was your wiki.
Link updated!
