### ISSUE TITLE
Provide an option to toggle on and off references in the reference plug in settings

### ISSUE THREAD

**Issue by arunnbabu81** [kebifurai/TiddlyResearch#11]
Since there are four different types of references in reference plug in of tiddly research, footer of some of the tiddlers get populated with too many references. It will be better if you provide an option to toggle on and off each type of reference separately in the reference plug in settings so that the user can decide which is needed depending on the use case

**Comment by postkevone** [comment]
I also experienced the too many references problem, next week I will update the reference plugin and add options to activate each reference type.

**Comment by postkevone** [comment]
Settings added to the reference plugin v1.0.3
