### ISSUE TITLE
Untitled tiddlers don't give usefull information

### ISSUE THREAD

**Issue by Shuenhoy** [kebifurai/TiddlyResearch#12]
Bullet point-based hierarchical note taking structure is great. However, there would be two many tiddlers without meaningless titles shown at places like recent tiddlers and references.

I would suggest giving them a field when generating and ignoring them from recent tiddlers based on this field. As for the references, I think displaying the top-level tiddlers a block belongs to instead of the block itself would be better. And a popup box with the contents of the block can be shown when mouses hover on the reference tag.

**Comment by postkevone** [comment]
You can already preview the references blocks at the bottom of a tiddler by hovering on them while holding the shift-key.

The title is set to an unique ID so that every node-tiddler can be completely independent from any other tiddler.
For the recent tab I might add an option to show/hide node tiddlers.

**Comment by Shuenhoy** [comment]
> You can already preview the references blocks at the bottom of a tiddler by hovering on them while holding the shift-key.
> 
> The title is set to an unique ID so that every node-tiddler can be completely independent from any other tiddler.
> For the recent tab I might add an option to show/hide node tiddlers.

The preview feature is awesome. But I think aggregation could make it easier to get the information.

For example, if we have one top-level tiddler named `A` and two blocks of `A` that refers to another tiddler `B`, named `c` and `d`. In the current version, there would be two references in `B`, with the unique id of `c` and `d`. However, we could not know what they are until we hover on them and preview them separately. 

If there is an aggregation mechanism. There could be only one reference `A` in `B`, and when we hover on it, the preview would be `c` and `d`(other blocks in `A` can be hidden here). Then we would roughly know what it is by reading the title of `A`, and we can know the exact blocks with preview.

**Comment by postkevone** [comment]
I think the aggregation function is great, but to implement it I would need to change the way the preview plugin works as well.
I will update this issue when I find a workaround.

**Comment by saqimtiaz** [comment]
The new `get-stream-root[]` filter would be useful here: https://saqimtiaz.github.io/streams/#Streams%200.2%20improvements%2FFilters

**Comment by postkevone** [comment]
This issue was resolved in https://github.com/kebifurai/tiddlystudy
