### ISSUE TITLE
Idea: modify Project Manager plugin to make it work with TiddlyResearch better

### ISSUE THREAD

**Issue by Shuenhoy** [kebifurai/TiddlyResearch#13]
The Project Manager stores the content of tasks in titles and justifies whether a tiddler is a task by `todo` tag. 

This means tasks are treated differently from a note block. I made some explorations by replacing the `tag[todo]` filter with `[regexp:text[^TODO ]]`. Then we can create tasks everywhere by writing down `TODO blah blah`. This is very similar to org-agenda.

![image](https://user-images.githubusercontent.com/2196156/96255281-396a5a80-0fe9-11eb-9666-3a57dd2e9fdb.png)

**Comment by postkevone** [comment]
This looks great! I will do some testing and probably add this feature with the next update!

**Comment by keelancook** [comment]
I also love this idea. I currently do not use the project manager function much because of this very reason.

**Comment by postkevone** [comment]
I already added this feature but I'm waiting for TW 5.1.23 to make a bigger release.

**Comment by keelancook** [comment]
Excellent! Looking forward to the release!

**Comment by postkevone** [comment]
I have decided to work on a different version of the Projects plugin to integrate better with Streams and the tiddlyresearch theme.
Unfortunately, you will have to wait a little bit more for the release.
