### ISSUE TITLE
Feature Request: Numbered Nodes

### ISSUE THREAD

**Issue by professionalPeter** [kebifurai/TiddlyResearch#14]
I find myself often wanting some nodes to be numbered instead of bullet points. It would be great if we had the option for a node to be displayed with either a bullet or a sequential number much like we can with wikiText.

**Comment by postkevone** [comment]
Thank you for your suggestion, unfortunately I am not the creator of the streams plugin (the one that makes nodes possible in tiddlywiki).
You might want to contact the original creator here: https://github.com/saqimtiaz/streams
