### ISSUE TITLE
Make the preview window configurable

### ISSUE THREAD

**Issue by keelancook** [kebifurai/TiddlyResearch#15]
Hello, recently started using your TW5 edition, and I'm enjoying its functionality.

One suggestion I have is to include configuration settings that make the preview window that pops on on shift+mousover customizable. I am using the bibtex and refnotes plugins for academic research. With them, I have a custom view of my reference notes that does not show up in the preview. 

I was able to edit the preview template to add what I needed with the help of Saq over at the Google group. However, having an option in the control panel to determine what is included in that preview would be a really great idea.

Here is a reference to my conversation at the google group for further explanation: [Refnotes/Bibtex modifications?](https://groups.google.com/g/tiddlywiki/c/sGldiq8BY0w)

**Comment by postkevone** [comment]
Adding a configuration to edit/add more template views to the preview plugin sounds like a great feature to enhance plugin compatibility.
Adding this in the next update!
