### ISSUE TITLE
Enhancement : Bi-directional linking to show content instead of UID

### ISSUE THREAD

**Issue by hfactor** [kebifurai/TiddlyResearch#16]
New nodes that are created inside Tiddlers a named with a Unique Number. I understand the need for a Unique number, but as a user, it would be easier if the Node shows Content as the title instead of UID. 

Attaching the current UI and proposed UI.
<img width="1792" alt="Screenshot 2020-10-31 at 3 18 35 PM" src="https://user-images.githubusercontent.com/1788677/97776272-c20dfc80-1b8c-11eb-84cc-0a79a6c3c817.png">
<img width="1792" alt="Screenshot 2020-10-31 at 3 21 18 PM" src="https://user-images.githubusercontent.com/1788677/97776273-c33f2980-1b8c-11eb-9ac7-fb3f37f430be.png">

_I started using TiddlyResearch (and TW5) just two days ago, hence I am not sure if this feature already exists._

**Comment by postkevone** [comment]
Fortunately there is already a macro inside the streams plugin that does exactly what you are asking for.
I will probably add a checkbox setting to the reference plugin to enable/disable this feature.

**Comment by hfactor** [comment]
Woah. Waiting for it <3
