### ISSUE TITLE
More horizontal space

### ISSUE THREAD

**Issue by pdroalves** [kebifurai/TiddlyResearch#18]
When I'm working on a single tiddler it occupies a quite small area on the left side of my screen. This looks like a waste of space, and sometimes it's a bit frustrating to not being able to resize it to occupy at least half of the entire available width.

I believe that this would be solved if the tiddler's width could be modified, manually or automatically, when there are enough screen space to fit all opened tiddlers.

**Comment by postkevone** [comment]
You can resize a tiddler's width and padding from: 

control panel > plugins > Krystal > settings

You can also make one tiddler occupy all the story view space by clicking the "maximize tiddler" button from the more actions menu:

![Screenshot_2020-11-10_10-37-03](https://user-images.githubusercontent.com/49175327/98616731-be266b00-2340-11eb-81e5-9151945d2bdc.png)

Let me know if this helped!

**Comment by pdroalves** [comment]
This helps a lot! Maybe a shortcut to facilitate the access to Krystal setup would be welcome, thou. A guideline that could be dragged using a mouse would be perfect.

The button to maximize and occupy all the view space seems a bit "green". I think it would be better if the user could set a different padding for a tiddler when it is maximized than when it is not. Looks like the current padding is the same in both cases, but when maximized the padding should be a bit larger. For instance, see what happens to the gray area on a LibreOffice Writer document when the windows is maximized and when it is not.

**Comment by postkevone** [comment]
Adding a guideline seems like a good idea but I think is better if you suggest this feature directly to the original creator and maintainer of the Krystal plugin: https://github.com/crazko/krystal/issues

Adding new functions to plugins that are still being developed might result in issues when a newer version gets released, and updating them might result in some tedious work.

> I think it would be better if the user could set a different padding for a tiddler when it is maximized than when it is not.

You can add more padding for maximize tiddlers by modifying the following tiddler:
`$:/plugins/rmnvsl/krystal/river.css`
And the following class:
`.krystal-tiddler__frame--maximized`
In there you could add a padding property and set it to match your preference, for example:
`padding: 0 150px;`

Let me know if this helped!
