### ISSUE TITLE
Maximum Call Stack Size Exceeded on naming a tiddler "DFS"

### ISSUE THREAD

**Issue by prashantsengar** [kebifurai/TiddlyResearch#19]
## Steps to recreate
Create a new tiddler named "DFS" (without the quotes). On opening it, you might notice a DFS of nodes, i.e, new nodes being created on next level without a limit.

Screenshot:
![image](https://user-images.githubusercontent.com/45726744/100761747-3f8d8c80-3419-11eb-8a37-2300f84ba71e.png)

**Comment by postkevone** [comment]
Are you using a non-modified version of tiddly research?
I can't replicate your error in mine:

![Untitled](https://user-images.githubusercontent.com/49175327/100812445-574c2b80-3480-11eb-80ad-aef4484d5b08.png)

Also, could you tell me what browser/method are you using to open your tiddlywiki file?

**Comment by prashantsengar** [comment]
Thanks for looking it up @kebifurai 
I am using a non-modified (no extra plugin) version of TiddlyResearch, just downloaded an empty slate yesterday and started working. Weirdly though, when I use another empty slate and do the same steps, it didn't cause any such issue. 

- Using TiddlyDesktop
- Enabled the under testing autocomplete plugin (did that for both the wikis but the second one worked)
- I have a few settings changed though in the first wiki, which I did while customizing. But all of them were from the control panel and nothing out of the box.

But I had this issue two times and thus I thought of reporting it. Both of the times it was with TR and not with other Tiddly wikis.

**Comment by prashantsengar** [comment]
Not able to reproduce it myself now.

**Comment by postkevone** [comment]
I could not reproduce it either, I will tag this as bug and close for the moment.
I will reopen this issue if other users experience the same error.
