### ISSUE TITLE
Are there instructions for the Anki integration?

### ISSUE THREAD

**Issue by JCalinawan** [kebifurai/TiddlyResearch#2]
Hello,
Thank you for this modification on Tiddlywiki. It looks great! Can you point me to instructions/walkthrough how I can connect this with Anki? I couldn't figure it out! Thank you.

**Comment by crazko** [comment]
Hi, have a look at the documentation here https://sobjornstad.github.io/TiddlyRemember/ that's a plugin behind the whole logic.

TLDR: you need to install Anki for desktop and add-on there, configure it. After that you'll be able to sync Anki data from Tiddly to your Anki desktop.

**Comment by postkevone** [comment]
Thank you @crazko for pointing it out.
Later this week I am going to release some animated GIF tutorials where I also show how to setup and create Anki cards.

**Comment by JCalinawan** [comment]
Thank you. I wanted to confirm...if I’m using tiddlywiki as a single html file (I’m using it through IOS), the Anki feature will not work, is that right? That feature requires node.js implementation? Thank you.

**Comment by postkevone** [comment]
Yes, that's correct. The wiki html file must comunicate with the Tiddly Remember anki plugin in order to sync your cards, you can do this only on a computer.
