### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tttdevelop** [kebifurai/TiddlyResearch#21]
To recreate; 

Open a TiddlyResearch example at https://kebifurai.github.io/TiddlyResearch/, click on folders -> Tutorial -> GIFs. Javascript error comes up. 

Tested on;

OS : Linux
Browser : Brave, Chrome and Firefox (all latest versions)

![Error TiddlyResearch](https://user-images.githubusercontent.com/50626259/103724681-8289e380-5007-11eb-9d2c-d76513f0b2d8.png)

Real Life Situations;

Came across this problem when working with my own tiddlers which makes this excellent version of tiddlywiki unusable.

**Comment by tttdevelop** [comment]
Update :

Disabling the plugin "tiddlyresearch-references: reference plugin" solves the problem, so the issue originates from this plugin.

Hopes this helps.

**Comment by postkevone** [comment]
This is because the reference plugins tries to create links from the gifs content (which are basically very long text).
Thank you for your report, I will release a quick fix today.

**Comment by postkevone** [comment]
Fixed with the v.1.0.5 version of the reference plugin.

**Comment by tttdevelop** [comment]
Great & Fast work !! Thanks. This is a very good implementation of Tiddlywiki.

**Comment by postkevone** [comment]
Thank you for your kind words!
