### ISSUE TITLE
Clarification: Is this a single file TiddlyWiki or do I need the take all the folders with me

### ISSUE THREAD

**Issue by angrystatic** [kebifurai/TiddlyResearch#24]
Excellent work!
I'm just moving over to TiddlyResearch as I'm limited in my tool selection due to 1) rules, 2) colleague buy in ramp 3) needs for simplicity.

The folders navigation system is key for number 2).

Sadly I'm a big fan of mind maps so I'll have to use a separate tiddlywiki for tiddlymaps. But that's not necessarily a bad thing.

What I'd like to know is, if I'm backing up or sharing a TiddlyResearch wiki, do I need the folders to go with it as it travels? (tiddlers + plugins)

![Screenshot 2021-03-31 121632](https://user-images.githubusercontent.com/33765814/113184499-de38c700-921a-11eb-8fd2-fb5cb47b80df.png)
![Screenshot 2021-03-31 121550](https://user-images.githubusercontent.com/33765814/113184500-de38c700-921a-11eb-9a61-b4ac181db583.png)

 Or are those included for completeness?

**Comment by postkevone** [comment]
Thank you for your kind words.

The folders are only needed if you use tiddlywiki on Node.js (they are outdated because I haven't updated them yet).
If you use tiddlywiki as a single html file you just need to backup that single file.

Hope this clarified your question :)

**Comment by angrystatic** [comment]
Yup! Thanks!
