### ISSUE TITLE
Dragging a block to a new tiddler

### ISSUE THREAD

**Issue by JCalinawan** [kebifurai/TiddlyResearch#5]
Hello,

I had a feature question. Is there a way to drag a tiddler block so it is reused and embedded in a new tiddler that one might be creating (like a draft of an article)? I just watched how you could do this in roam and wondered if there is a way to do that. If not possible, is there a way to copy the title of the tiddler block so I could type it within {{tiddler block Title}}? 

I really love what you’ve done in TiddlyResearch. You just have to change the way you think about a “tiddler.” In your modification, the tiddler is really a block. It’s ingenious. Thank you for creating it!

**Comment by postkevone** [comment]
Thanks for the support.
In the current version you can already transclude blocks in other tiddlers using {{block title}}, this is a standard feature of tiddlywiki.
In the next update I'm going to enable transclusion for entire tiddlers, stay tuned!
