### ISSUE TITLE
Is it possible to include a “forward-link” feature?

### ISSUE THREAD

**Issue by JCalinawan** [kebifurai/TiddlyResearch#7]
Hi,

I’m wondering if there would be a benefit in adding something like “forward-links”. I have 10 years worth of Evernote/ googlekeep notes and I’m importing them into TiddlyResearch. They are obviously not linked to any tiddlers.

What would be great actually is if these unlinked notes would show potential tiddlers/tags that they could link to. It’s really just the “mirror image“ of the back-link feature that you already implemented. So TiddlyResearch would suggest potential links and by clicking these links, it would then create the bi-directional link for real. What do you think? Would this be useful?
Perhaps I’m not seeing the problems with this approach (or maybe it could already be done using another plugin?), but it sounds really good to me. :-)

Thank you for considering.

**Comment by postkevone** [comment]
Thanks for the suggestion.
I don't know how you are importing notes from evernote and googlekeep, but I guess you are doing it by using the standard TiddlyWiki format and not the Streams (single nodes) one.
Tiddly Research already supports unlinked references, so if you were to import a lot of notes it will automatically create links for mentions in the title/in the text (color red and grey). From there you could navigate through your notes and decide what you want to be a backlink and what not. You can also speed up the process by selecting a word and use the "shift + L" shortcut to quickly create a backlink.

**Comment by JCalinawan** [comment]
The unlinked referencing feature is great, but I was suggesting the mirror-image of that feature. For example, say I have a tag name “mythology” or a tiddler B entitled “mythology.”  I then create a new tiddler C where I use the word “mythology” in the body field. The unlinked referencing feature will only show the unlinked reference of tiddler C in tiddler B. What I was suggesting was if tiddler C would also show the unlinked reference to tiddler B (and to the tag “mythology”). In this way, I can think of whether I want to connect tiddler C to tiddler B or tag.

Currently, tiddler B shows the unlinked reference from tiddler C, but tiddler C does not show the unlinked reference to tiddler B. In a way, it speeds up the autocompletion linking feature that you are working on (I think) because you’ll know as a user exactly what to type in the [[ ]] code.

I think this would be really useful.  This is like what Zettelkasten recommends, i.e.  linking each new note to something that is already in the slipbox. If this can  be done in the existing implementation, I would love to find out how. Maybe I’m just not seeing it. Thank you.

**Comment by postkevone** [comment]
I now understand what you meant by “mirror image“ and is not a bad idea.
It would work like a suggestion to create a backlink from a mention, I still don't know what is the best approach to implement this but I'll think about it!

**Comment by postkevone** [comment]
A temporary solution would be installing the Freelink plugin, available in the official repository of tiddlywiki.
When you import you notes in standard tiddlywiki format, the plugin will automatically search for references in the text and will automatically create links to mentioned notes (they are not backlinks).
You could use this function to explore your notes and decide what you want to make a backlink and what not.
Hope this helps!

**Comment by JCalinawan** [comment]
Thanks for this tip! I tried Freelink and it does work, but with my html file at 30MB it didn't work. It's curious because at this size, tiddlyresearch is perceptually as fast as when it was only 6MB (including all the system/shadow tiddlers). My file doesn't even have images or attachments. There is a lot of unnecessary text in there so conceivably over time as I clean up the data and delete unnecessary notes, the file size will go down a little bit or stay the same. In your view, should I just go with roamresearch if I'm going to have something this large? I really don't want to, but maybe there is no choice... Thank you!

**Comment by postkevone** [comment]
In the freelinks plugin description it says that link generation can be slow with large wikis, so maybe that's the case.
If you can afford it and don't need the srs function switching to roam research or other alternatives might be a good idea, 
but I don't know if its loading times are fast when having to deal with a lot of documents.
