### ISSUE TITLE
How to make block ref and block embed ? 

### ISSUE THREAD

**Issue by ghost** [kebifurai/TiddlyResearch#8]
Thanks

**Comment by postkevone** [comment]
You can either drag and drop a block while pressing shift to embed it in another tiddler.
Or you can also use the syntax {{block name||embed}}.
For more info you can check .Keyboard Shortcuts > General Shortcuts > Transclude a tiddler/node
Here's a direct link: https://kebifurai.github.io/TiddlyResearch/#.Keyboard%20Shortcuts

Hope this helps :)

**Comment by postkevone** [comment]
You can reference a block by writing its name inside double square brackets.
Example: [[20200902121610264]]

You can access the block title by clicking the dot you see on the left of every node.

**Comment by ghost** [comment]
How about block embed ?

**Comment by postkevone** [comment]
> You can either drag and drop a block while pressing shift to embed it in another tiddler.
> Or you can also use the syntax {{block name||embed}}.
> For more info you can check .Keyboard Shortcuts > General Shortcuts > Transclude a tiddler/node
> Here's a direct link: https://kebifurai.github.io/TiddlyResearch/#.Keyboard%20Shortcuts

If this doesn't resolve your doubt, can you explain me what you mean by "block embed"?

**Comment by postkevone** [comment]
Closing this for now.
Feel free to re-open if you have any doubts about block referencing.
