### ISSUE TITLE
Request: Way on node.js server?

### ISSUE THREAD

**Issue by dv2s4z7** [kebifurai/TiddlyResearch#9]
Wow, this is a great looking project!  I prefer running tw on node rather than the HTML file.  I don't see instructions on how to do this (assume it would likely be a little manual).  Could you kindly confirm if this is/can be done and - if not - if it's on the roadmap?  Thanks!

**Comment by postkevone** [comment]
Tomorrow I'm going to upload the node.js directory into the github repository, so that node.js users can import the plugins folder directly!

**Comment by postkevone** [comment]
Uploaded the node.js files

**Comment by dv2s4z7** [comment]
@kebifurai 
Perfect! Thanks!!
